" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Monaco:h14            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set lines=35 columns=120          " Window dimensions.

set guioptions-=r                 " Don't show right scrollbar
set guioptions-=L                 " Hide left scrollbar

if has('mac')
    set guifont=Monaco:h14
elseif has('unix')
    set guifont=Courier\ New\ 11
endif
